name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        env:
          NODE_URL: ${{ secrets.NODE_URL }}
        run: |
          npm install --no-lockfile --force
          npm run compile
          npm run test
